spring.application.name=medicare

spring.datasource.url=jdbc:postgresql://localhost:5432/medicare
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
jwt.refresh.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=${MAIL_PASSWORD}

google.client.id=${GOOGLE_CLIENT_ID}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true