spring.application.name=medicare

# ===============================
# DATABASE
# ===============================
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
jwt.refresh.expiration=86400000

# ===============================
# EMAIL
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# GOOGLE OAUTH
# ===============================
google.client.id=${GOOGLE_CLIENT_ID}

# ===============================
# FRONTEND
# ===============================
app.frontend.url=${FRONTEND_URL:http://localhost:5173}
ml.service.url=${ML_SERVICE_URL}
